package studentOrientation.util;

public enum ActivitiesEnum {
    SOM_FOOT,
    WATSON_FOOT,
    CS240_FOOT,
    CS350_FOOT,
    EVENTCENTER_FOOT,
    UNIVERSITYUNION_FOOT,
    CIW_FOOT,
    MOUNTAINVIEW_FOOT,
    SOM_BUS,
    WATSON_BUS,
    CS240_BUS,
    CS350_BUS,
    EVENTCENTER_BUS,
    UNIVERSITYUNION_BUS,
    CIW_BUS,
    MOUNTAINVIEW_BUS,
	BUILDING,
	CAFETERIA,
	GIFT,
	LECTURE;
}
